### ISSUE TITLE
안녕하세요 소스 질문드립니다.

### ISSUE THREAD

**Issue by YooSungHyun** [Junghwan-brian/Dual_Stage_Attention_RNN#1]
attention을 계산할때, hidden_state와 cell_state를 concat하신 특별한 이유라도 있나요?

제가 알고있는 attention은 hidden_state만 이용하는 것으로 알고있는데, 혹시 뭐 경험상 cell_state까지 concat하면 정보가 더 확장되서 잘맞았다라거나 하는 경험적인 이유에서 concat하신건지 궁금합니다.

**Comment by YooSungHyun** [comment]
논문을 전부다 읽어본건 아직 아니지만 짤막하게 읽어보던중 hidden과 cell state를 concat하는 부분이 있더군요 해결되었습니다. 감사합니다.

**Comment by Junghwan-brian** [comment]
네 논문에도 나와있고 보통 두개를 concat하면 더 잘되기도 합니다. 하지만 연산이 늘어나서 시간이 오래걸리는 단점도 있습니다. 어텐션은 하기 나름이라 사실 여러 방법을 써보는게 제일 좋은 것 같아요. 글 읽어주셔서 감사합니다.내 Galaxy에서 보냄
-------- 원본 이메일 --------발신: YooSungHyun ***@***.***> 날짜: 21/3/16  오후 3:01  (GMT+09:00) 받은 사람: Junghwan-brian/Dual_Stage_Attention_RNN ***@***.***> 참조: Subscribed ***@***.***> 제목: Re: [Junghwan-brian/Dual_Stage_Attention_RNN] 안녕하세요 소스 질문드립니다. (#1) 

논문을 전부다 읽어본건 아직 아니지만 짤막하게 읽어보던중 hidden과 cell state를 concat하는 부분이 있더군요 해결되었습니다. 감사합니다.

**Comment by YooSungHyun** [comment]
안그래도 지금 현업에다 적용하던 중 98일치 24시간 데이터를 20000배치정도 학습해야되는데 1 window 씩 움직이면서 학습시키려니 인코더 디코더에서도 시간이 꽤나 오래걸리더라고요,

더군다나 49일치 데이터를 decoder로 넣어서 49일치를 예측해야하는데, 예제는 1개씩만 예측하는지라 소스를 받아서 수정하는데도 좀 애먹고 있네요....ㅋㅋㅋ
빠르게 수정하려면 어느부분을 보면 될지 좀 힌트라도 주실 수 있을까요

대부분 외국인들 짠 소스 보면 attention부분은 그냥 tf에서 제공하는거 쓰거나 하는 예제가 많았는데, 거의 논문이랑 대조해보니까 소스도 순수하게 쌓아올리신거같고 대단하신분 같습니다 실력이 부럽네요...ㅋㅋㅋ

**Comment by YooSungHyun** [comment]
확실히 어텐션 weigth가 인풋과 디코더에서 전부 쓰이기 때문에, time-series를 길게 잡으면 길게 잡을수록
컴퓨팅 리소스 소모가 정말 말도안되네요...;; 24시간씩 98일해서 2000로우 이상 잡으니 거의 컴퓨터가 뻗어버리는군요....ㅋㅋㅋ
진짜 짧은 단기간예측을 매우 정확하게 해야될 것 아니면 장기간 forecasting같은 경우에는 현업에 적용이 좀 힘들지 않을까 싶습니다.

그래도 48시간으로 24시간 디코딩써서 24시간 forecasting하는건 꽤나 흥미로는 결과값을 얻어낼 수 있었습니다. ㅋㅋㅋㅋ

지금 짜여져있는건 단순 encoder decoder lstm이라서 좀 개선해보려고 한거였는데

그냥 어텐션 하나하는 RNN으로 돌아가야할까봐요~ 그럼 저는 이만~

**Comment by Junghwan-brian** [comment]
네 sequence 가 너무 길면 이 방법은 힘들고 차라리 many-to-many lstm 같은 간단한 방법이 나을 것 같고  transformer 계열로 가시는 것도 괜찮을 것 같아요. 건투를 빕니다!내 Galaxy에서 보냄
-------- 원본 이메일 --------발신: YooSungHyun ***@***.***> 날짜: 21/3/17  오후 7:24  (GMT+09:00) 받은 사람: Junghwan-brian/Dual_Stage_Attention_RNN ***@***.***> 참조: Junghwan-brian ***@***.***>, Comment ***@***.***> 제목: Re: [Junghwan-brian/Dual_Stage_Attention_RNN] 안녕하세요 소스 질문드립니다. (#1) 
확실히 어텐션 weigth가 인풋과 디코더에서 전부 쓰이기 때문에, time-series를 길게 잡으면 길게 잡을수록
컴퓨팅 리소스 소모가 정말 말도안되네요...;; 24시간씩 98일해서 2000로우 이상 잡으니 거의 컴퓨터가 뻗어버리는군요....ㅋㅋㅋ
진짜 짧은 단기간예측을 매우 정확하게 해야될 것 아니면 장기간 forecasting같은 경우에는 현업에 적용이 좀 힘들지 않을까 싶습니다.
그래도 48시간으로 24시간 디코딩써서 24시간 forecasting하는건 꽤나 흥미로는 결과값을 얻어낼 수 있었습니다. ㅋㅋㅋㅋ
지금 짜여져있는건 단순 encoder decoder lstm이라서 좀 개선해보려고 한거였는데
그냥 어텐션 하나하는 RNN으로 돌아가야할까봐요~ 그럼 저는 이만~

**Comment by YooSungHyun** [comment]
최근에 제가 단일 Attention부터 Transformer까지 넘나들며 Time-Series Forecasting을 해보려고 노력을 했는데요,
결과부터 말씀드리면, 아직은 일반 현업수준에서 도입하기엔 조금 시기상조인 것 같다.라는 의견을 드리고 싶습니다.

https://www.reddit.com/r/MachineLearning/comments/ckaji4/d_transformers_for_time_series_data/
레딧에보면 뭐 2019년 8월경 아티클이긴 하나,
Attention이 일반적으로 국소부위를 집중하다보니, 계절성을 고려하지 못하는 점과, 크기의 제한이 있는 단어를 위해 고도화된 알고리즘이기 때문에, 무한히 가능한 int or float 데이터를 처리하는데는 무리가 있다.
vs
아닌데? 우리가 찾아보니까 아티클은 있는데? + 내가 아는 지인은 transformer 쓰고 있다더라.
의 대립구도인 것을 확인할 수 있었고,

관련된 내용으로는
https://towardsdatascience.com/attention-for-time-series-classification-and-forecasting-261723e0006d
문서를 보면 충분히 가능한 것은 같으나, 2020년 8월에야 관련된 github 소스 페이지가 링크로 추가되었네요....ㅋㅋ

https://arxiv.org/pdf/1907.00235.pdf
논문에서 나오는 bottleneck과 계절성이 무시되는 현상에 대해서 잘 고려해야함을 시사하고 있네요

https://towardsdatascience.com/the-time-series-transformer-2a521a0efad3
이런 아티클들도 있던데, 아예 시간을 vector로 표현하는 푸리에 변환을 이용한 방법들도 활용을 하던데,

지금 저는 연구를 진행중인 것이 아니라, 실제 현업 서비스에 운영으로 사용해야되다보니, 이정도 수준의 알고리즘이 필요할지에 대한 Trade-Off 부분이 분명 존재하는 것 같습니다.

현재 그냥 BI-LSTM VAE로 개발되어있는 모델을 그래도 나름 잘 활용하고 있는데요,
제가 볼때는 연구에 소요되는 시간과 실제 작업에 대한 리스크등을 고려해봤을때, 마치 VGG/RESNET이나 BERT같은 대놓고 레퍼런스가 확실한 알고리즘들이 공개되기 전에는
시계열 데이터 회귀 예측에 대한 주제에서는 Transformer나 Attention과 같은 부분은 조금 적용 시 고려해야될 부분이 많지 않나 사료됩니다. 
(현재 저희 현업 데이터에는 적합하지 않은 것 같더라구요 ㅎㅎ)

작성자님의 아티클도 너무 재밌고 알차게 잘봤고, 학문적으로 공유도 된거같아 감사한마음도 있고, 즐거운 마음도 있었기에,
제가 찾아보고 고민해보고 느낀점을 공유드립니다.

제가 지식이 짧아 맞게 이해한 것인진 모르겠으나, 이렇게 공유함으로써 새로운 지식을 탐구하고 발견해나갈 수 있다면 좋겠습니다.
사실 이미 다 해보시고 넘어가신거라, 관심이 없으실수도 있는데 제가 괜한 오지랖인건 아닌가 싶기도 하네요 ㅎㅎ
감사합니다!

**Comment by Junghwan-brian** [comment]
좋은 내용 공유해주셔서 감사합니다. ㅎㅎ 공부를 정말 열심히 하신 것 같네요.
저는 Regression 문제를 풀고 있는데 현업에서의 문제와 연구간의 괴리를 많이 느낍니다.
BI-LSTM VAE 으로도 충분한 성능이 나온다면 그대로 사용하셔도 좋을 것 같네요. 
혹시 계절성이 있는 시계열 데이터를 처리하고 계시다면 Neural ODE 논문을 추천드립니다.
https://arxiv.org/abs/1806.07366 
유명한 논문이라 보셨을지도 모르겠네요 ㅎㅎ.

앞으로 좋은 성과 내시길 바라겠습니다.

감사합니다.
 
-----Original Message-----
