### ISSUE TITLE
한가지 더 질문드리고 싶은게 있습니다! 바다나우 어텐션

### ISSUE THREAD

**Issue by YooSungHyun** [Junghwan-brian/Dual_Stage_Attention_RNN#2]
바다나우에서 values값은 encoding의 은닉상태를 사용하는 것으로 알고있는데요,
(바다나우 뿐만 아니라 dot_product에서도..!)

혹시 h를 사용하실때 hidden_state와 cell_state를 합쳐서 사용하신 특별한 이유가 있으신가요?
제생각에는 hidden_state만 사용하는게 맞는게 아닌가 해서요!

혹시 이 역시도 DA-RNN논문에서의 hidden concat cell 하는 부분을 차용하신 건가요?

**Comment by Junghwan-brian** [comment]
네 보통 hidden state만 사용하는데 cell state를 사용하면 보통 성능이 증가하는 경향이 있습니다. 하지만 시간이 늘어나고 task마다 그 영향이 다르긴 해서 실험을 한번 해보시는게 가장 좋습니다.내 Galaxy에서 보냄
-------- 원본 이메일 --------발신: YooSungHyun ***@***.***> 날짜: 21/3/23  오후 1:56  (GMT+09:00) 받은 사람: Junghwan-brian/Dual_Stage_Attention_RNN ***@***.***> 참조: Subscribed ***@***.***> 제목: [Junghwan-brian/Dual_Stage_Attention_RNN] 한가지 더 질문드리고 싶은게 있습니다! 바다나우 어텐션 (#2) 
바다나우에서 values값은 encoding의 은닉상태를 사용하는 것으로 알고있는데요,
(바다나우 뿐만 아니라 dot_product에서도..!)
혹시 h를 사용하실때 hidden_state와 cell_state를 합쳐서 사용하신 특별한 이유가 있으신가요?
제생각에는 hidden_state만 사용하는게 맞는게 아닌가 해서요!
혹시 이 역시도 DA-RNN논문에서의 hidden concat cell 하는 부분을 차용하신 건가요?
